import mysql.connector as mc

ob=mc.connect(host="localhost",user="root",passwd="sql123")
c=ob.cursor()
c.execute("create database project;")
print("Database created")

ob.close()
c.close()
ob=mc.connect(host="localhost",user="root",passwd="sql123", database='project')
c=ob.cursor()
c.execute("CREATE TABLE studentinfo1(name VARCHAR(30),age INT(3),gender VARCHAR(10),house VARCHAR(14),username VARCHAR(20),password VARCHAR(20))")
c.execute("CREATE TABLE teacherinfo1(name VARCHAR(30),username VARCHAR(30),password VARCHAR(20),event VARCHAR(10))")
c.execute("CREATE TABLE art(name VARCHAR(30))")
c.execute("CREATE TABLE dance(name VARCHAR(30))")
c.execute("CREATE TABLE quiz(name VARCHAR(30))")
c.execute("CREATE TABLE music(name VARCHAR(30))")
c.execute("CREATE TABLE theatre(name VARCHAR(30))")
c.execute("CREATE TABLE eventdetails(event VARCHAR(10) primary key,dateofevent date,venue VARCHAR(30),periodno int)")
c.execute("insert into eventdetails values('art','2021-10-25','Art Room',9)")
c.execute("insert into eventdetails values('dance','2021-07-10','Dance Room',9)")
c.execute("insert into eventdetails values('music','2021-06-20','Mini audi',9)")
c.execute("insert into eventdetails values('quiz','2021-10-17','AV room',9)")
c.execute("insert into eventdetails values('theatre','2021-09-29','Mini audi',9)")
ob.commit()
ob.close()
c.close()
